language: rust
sudo: false

matrix:
  include:
    # Stable
    - os: linux
      rust: stable
    - os: osx
      rust: stable
    # Beta
    - os: linux
      rust: beta
    - os: osx
      rust: beta
    # Nightly
    - os: linux
      rust: nightly
    - os: osx
      rust: nightly

# Install Python for integration tests
addons:
  apt:
    packages:
      - python

# Fetch the big list of naughty strings
before_script:
  - >
    wget -O ./tests/blns/blns.inden.tex
    https://raw.githubusercontent.com/minimaxir/big-list-of-naughty-strings/master/blns.txt

script:
  - cargo --version
  - rustc --version
  - cargo build
  - cargo test
  - cargo run ./tests/
  - cargo run ./tests/empty_folder/  # Check how indentex handles empty folders
  - python ./tests/compare_to_reference.py
