os: Visual Studio 2015

environment:
  global:
    PROJECT_NAME: indentex
  matrix:
  # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc
  # Beta 64-bit MSVC
    - channel: beta
      target: x86_64-pc-windows-msvc
  # Nightly 64-bit MSVC
    - channel: nightly
      target: x86_64-pc-windows-msvc

matrix:
  allow_failures:
    - channel: nightly

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

before_test:
  - >
    appveyor DownloadFile
    https://raw.githubusercontent.com/minimaxir/big-list-of-naughty-strings/master/blns.txt
    -FileName ./tests/blns/blns.inden.tex

test_script:
  - set RUSTFLAGS='-C target-feature=+crt-static'
  - cargo build
  - cargo test
  - cargo run -- -v ./tests/
  - cargo run -- -v ./tests/empty_folder/  # Check how indentex handles empty folders
  - python ./tests/compare_to_reference.py
