os: Visual Studio 2015
platform: x64
cache:
  - '%USERPROFILE%\.cargo'

environment:
  global:
    PROJECT_NAME: indentex
  matrix:
  # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc
      static: 0
  # Beta 64-bit MSVC
    - channel: beta
      target: x86_64-pc-windows-msvc
      static: 0
  # Nightly 64-bit MSVC
    - channel: nightly
      target: x86_64-pc-windows-msvc
      static: 0
  # Nightly 64-bit MSVC + static CRT linking
    - channel: nightly
      target: x86_64-pc-windows-msvc
      static: 1

matrix:
  allow_failures:
    - channel: nightly

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - if [%static%]==[1] (choco install pandoc)
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build_script:
  - >
    if [%static%]==[1] (
      cargo build --release
      cd .\packaging\windows_wix
      pip install -r requirements.txt
      powershell .\make_installer.ps1
    )

before_test:
  - >
    appveyor DownloadFile
    https://raw.githubusercontent.com/minimaxir/big-list-of-naughty-strings/master/blns.txt
    -FileName ./tests/blns/blns.inden.tex

test_script:
  - if [%static%]==[1] (set "RUSTFLAGS=-C target-feature=+crt-static")
  - cargo build
  - cargo test
  - cargo run -- -v ./tests/
  - cargo run -- -v ./tests/empty_folder/  # Check how indentex handles empty folders
  - python ./tests/compare_to_reference.py

artifacts:
  - path: packaging\windows_wix\indentex.msi
    name: indentex_installer

deploy:
  - provider: GitHub
    artifact: indentex_installer
    auth_token: 9QypfhMr/2TVe8WSZNepJafno+SmV+DmNv+GczEgQ8geVN2Wz0pvUZDkzp4PdcsV
    on:
      appveyor_repo_tag: true
      appveyor_repo_name: mp4096/indentex
      channel: nightly
      target: x86_64-pc-windows-msvc
      static: 1
