[package]
name = "indentex"
version = "0.4.0"
authors = ["Mikhail Pak <mikhail.pak@tum.de>"]
license = "MIT"
description = "An indentation-based superset of LaTeX"
readme = "README.md"
keywords = ["latex"]
publish = false


[dependencies]
ansi_term = "^0.9.0"
clap = "^2.23.3"
globset = "^0.1.3"
ignore = "^0.1.9"
nom = "^2.1.0"
rayon = "^0.7.0"


[profile.release]
opt-level = 3
lto = true
debug-assertions = false
