[package]
name = "indentex"
version = "0.3.2"
authors = ["Mikhail Pak <mikhail.pak@tum.de>"]
license = "MIT"
description = "An indentation-based superset of LaTeX"
readme = "README.md"
keywords = ["latex"]
publish = false


[dependencies]
ansi_term = "^0.9.0"
clap = "^2.20.0"
globset = "^0.1.2"
ignore = "^0.1.6"
nom = "^2.0.1"


[profile.release]
opt-level = 3
lto = true
debug-assertions = false
